---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
  {{- if .Values.tap.resourcelabels }}
    {{- toYaml .Values.tap.resourcelabels | nindent 4 }}
  {{- end }}
  name: '{{ .Values.tap.selfnamespace }}'
spec: {}
status: {}
