---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
  {{- if .Values.tap.labels }}
    {{- toYaml .Values.tap.labels | nindent 4 }}
  {{- end }}
  name: {{ .Values.tap.selfnamespace }}
spec: {}
status: {}
