---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
  {{- if .Values.tap.resourcelabels }}
    {{- toYaml .Values.tap.resourcelabels | nindent 4 }}
  {{- end }}
  name: kubeshark-cluster-role-binding
  namespace: '{{ .Values.tap.selfnamespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeshark-cluster-role
subjects:
  - kind: ServiceAccount
    name: kubeshark-service-account
    namespace: '{{ .Values.tap.selfnamespace }}'
