apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: kubeshark-front
    kubeshark-created-by: kubeshark
    kubeshark-managed-by: kubeshark
  name: '{{ .Values.tap.selfnamespace }}'
  namespace: kubeshark
spec:
  containers:
    - env:
        - name: REACT_APP_DEFAULT_FILTER
          value: ' '
        - name: REACT_APP_HUB_HOST
          value: ' '
        - name: REACT_APP_HUB_PORT
          value: "8898"
      image: '{{ .Values.tap.docker.registry }}/front:{{ .Values.tap.docker.tag }}'
      imagePullPolicy: '{{ .Values.tap.docker.imagePullPolicy }}'
      name: kubeshark-front
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 1
        successThreshold: 1
        tcpSocket:
          port: 80
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 750m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 50Mi
  dnsPolicy: ClusterFirstWithHostNet
  imagePullSecrets: '{{ .Values.tap.docker.imagepullsecrets }}'
  serviceAccountName: kubeshark-service-account
  terminationGracePeriodSeconds: 0
  tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
status: {}
