---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
  {{- if .Values.tap.resourcelabels }}
    {{- toYaml .Values.tap.resourcelabels | nindent 4 }}
  {{- end }}
  name: kubeshark-front
  namespace: '{{ .Values.tap.selfnamespace }}'
spec:
  ports:
    - name: kubeshark-front
      port: 80
      targetPort: 80
  selector:
    app: kubeshark-front
  type: NodePort
status:
  loadBalancer: {}
