---
{{- if .Values.tap.persistentstorage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
  {{- if .Values.tap.resourcelabels }}
    {{- toYaml .Values.tap.resourcelabels | nindent 4 }}
  {{- end }}
  name: kubeshark-persistent-volume-claim
  namespace: {{ .Values.tap.selfnamespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.tap.storagelimit }}
  storageClassName: {{ .Values.tap.storageclass }}
status: {}
{{- end }}
