apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: kubeshark-worker-daemon-set
    kubeshark-created-by: kubeshark
    kubeshark-managed-by: kubeshark
  name: '{{ .Values.tap.selfnamespace }}'
  namespace: kubeshark
spec:
  selector:
    matchLabels:
      app: kubeshark-worker-daemon-set
      kubeshark-created-by: kubeshark
      kubeshark-managed-by: kubeshark
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubeshark-worker-daemon-set
        kubeshark-created-by: kubeshark
        kubeshark-managed-by: kubeshark
      name: kubeshark-worker-daemon-set
      namespace: kubeshark
    spec:
      containers:
        - command:
            - ./worker
            - -i
            - any
            - -port
            - "8897"
            - -servicemesh
            - -tls
            - -procfs
            - /hostproc
          image: '{{ .Values.tap.docker.registry }}/worker:{{ .Values.tap.docker.tag }}'
          imagePullPolicy: '{{ .Values.tap.docker.imagePullPolicy }}'
          name: kubeshark-worker-daemon-set
          resources:
            limits:
              cpu: '{{ .Values.tap.resources.worker.cpu-limit }}'
              memory: '{{ .Values.tap.resources.worker.memory-limit }}'
            requests:
              cpu: '{{ .Values.tap.resources.worker.cpu-requests }}'
              memory: '{{ .Values.tap.resources.worker.memory-requests }}'
          securityContext:
            capabilities:
              add:
                - NET_RAW
                - NET_ADMIN
                - SYS_ADMIN
                - SYS_PTRACE
                - DAC_OVERRIDE
                - SYS_RESOURCE
              drop:
                - ALL
          volumeMounts:
            - mountPath: /hostproc
              name: proc
              readOnly: true
            - mountPath: /sys
              name: sys
              readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      serviceAccountName: kubeshark-service-account
      terminationGracePeriodSeconds: 0
      tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
      volumes:
        - hostPath:
            path: /proc
          name: proc
        - hostPath:
            path: /sys
          name: sys
