name: ci
on:
  push:
    branches:
      - 'develop'
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: build push docker image to gcr 
        uses: sendinblue/build-and-push-action@main
        with:
          image-name: 'mizu/${GITHUB_REF##*/}'
          gcp-project-id: 'up9-docker-hub'
          gcp-service-account-key: ${{ secrets.GCR_JSON_KEY }}
          
